# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dfs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dfs.proto',
  package='dfs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tdfs.proto\x12\x03\x64\x66s\"!\n\x11\x43reateFileRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"\"\n\x0f\x43reateFileReply\x12\x0f\n\x07message\x18\x01 \x01(\t2C\n\x03\x44\x46S\x12<\n\nCreateFile\x12\x16.dfs.CreateFileRequest\x1a\x14.dfs.CreateFileReply\"\x00\x62\x06proto3')
)




_CREATEFILEREQUEST = _descriptor.Descriptor(
  name='CreateFileRequest',
  full_name='dfs.CreateFileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='dfs.CreateFileRequest.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=51,
)


_CREATEFILEREPLY = _descriptor.Descriptor(
  name='CreateFileReply',
  full_name='dfs.CreateFileReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='dfs.CreateFileReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['CreateFileRequest'] = _CREATEFILEREQUEST
DESCRIPTOR.message_types_by_name['CreateFileReply'] = _CREATEFILEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateFileRequest = _reflection.GeneratedProtocolMessageType('CreateFileRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEFILEREQUEST,
  __module__ = 'dfs_pb2'
  # @@protoc_insertion_point(class_scope:dfs.CreateFileRequest)
  ))
_sym_db.RegisterMessage(CreateFileRequest)

CreateFileReply = _reflection.GeneratedProtocolMessageType('CreateFileReply', (_message.Message,), dict(
  DESCRIPTOR = _CREATEFILEREPLY,
  __module__ = 'dfs_pb2'
  # @@protoc_insertion_point(class_scope:dfs.CreateFileReply)
  ))
_sym_db.RegisterMessage(CreateFileReply)



_DFS = _descriptor.ServiceDescriptor(
  name='DFS',
  full_name='dfs.DFS',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=89,
  serialized_end=156,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateFile',
    full_name='dfs.DFS.CreateFile',
    index=0,
    containing_service=None,
    input_type=_CREATEFILEREQUEST,
    output_type=_CREATEFILEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DFS)

DESCRIPTOR.services_by_name['DFS'] = _DFS

# @@protoc_insertion_point(module_scope)
